{% set name = "whey-pth" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/whey-pth-{{ version }}.tar.gz
  sha256: 088a60ab33575b75694be93a042a5cd83372ab082dfc07f79ace7d007fd5e4a3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - dom-toml >=0.4.0
    - python >={{ python_min }}
    - whey >=0.0.15

test:
  imports:
    - whey_pth
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/repo-helper/whey-pth
  summary: Extension to whey to support .pth files.
  license: MIT
  license_file: LICENSE
  doc_url: https://whey-pth.readthedocs.io/en/latest

extra:
  recipe-maintainers:
    - domdfcoding
